services:
  react-app:
    container_name: react-app
    image: node:24-slim
    working_dir: /app
    volumes:
      - .:/app
      - my_node_modules:/app/node_modules 
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"


volumes:
  my_node_modules: